#ifndef MMN_CHARACTER_MACRO_INCLUDED
#define MMN_CHARACTER_MACRO_INCLUDED

#define STANDARD_SHADING 0
#define MONSTER_SHADING 1
#define SKIN_BODY_SHADING 2
#define DEEP_SHADING 3
#define STOCKINGS_SHADING 4
#define SKIN_FACE_SHADING 5

#define OUTLINE_COLOR_MULTIPLY 0
#define OUTLINE_COLOR_OVERRIDE 1

#define IS_TRUE(value) (value > 0.5)
#define IS_FALSE(value) (value <= 0.5)

#endif // MMN_CHARACTER_MACRO_INCLUDED
