#ifndef MMN_CHARACTER_MACRO_INCLUDED
#define MMN_CHARACTER_MACRO_INCLUDED

#define _SHADINGTYPE_STANDARD_VALUE 0
#define _SHADINGTYPE_MONSTER_VALUE 1
#define _SHADINGTYPE_DEEP_VALUE 2
#define _SHADINGTYPE_SKINBODY_VALUE 3
#define _SHADINGTYPE_SKINFACE_VALUE 4
#define _SHADINGTYPE_STOCKING_VALUE 5

#define OUTLINE_COLOR_MULTIPLY 0
#define OUTLINE_COLOR_OVERRIDE 1

#define IS_TRUE(value) (value > 0.5)
#define IS_FALSE(value) (value <= 0.5)

#endif // MMN_CHARACTER_MACRO_INCLUDED
